/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as base from "./base";

export type { base };
export type { CloudRecoveryModule } from "./CloudRecoveryModule";
export type { SocialRecoveryModule } from "./SocialRecoveryModule";
