/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EOAValidator } from "./EOAValidator";
export type { TEEValidator } from "./TEEValidator";
