/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as iHookSol from "./IHook.sol";
import type * as iValidatorSol from "./IValidator.sol";

export type { iHookSol };

export type { iValidatorSol };
export type { IClave } from "./IClave";
export type { IClaveRegistry } from "./IClaveRegistry";
export type { IInitable } from "./IInitable";
export type { IModule } from "./IModule";
