/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TokenCallbackHandler,
  TokenCallbackHandlerInterface,
} from "../../../../../@account-abstraction/contracts/samples/callback/TokenCallbackHandler";
import type { NonPayableOverrides } from "../../../../../common";
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC1155BatchReceived",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC1155Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "tokensReceived",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610342908161001c8239f35b600080fdfe60808060405260048036101561001457600080fd5b600091823560e01c90816223de291461020757816301ffc9a71461019b57508063150b7a0214610144578063bc197c81146100b65763f23a6e611461005857600080fd5b346100b25760a03660031901126100b25761007161027c565b5061007a610297565b5060843567ffffffffffffffff81116100ae5761009a92503691016102ad565b505060405163f23a6e6160e01b8152602090f35b8280fd5b5080fd5b50346100b25760a03660031901126100b2576100d061027c565b506100d9610297565b5067ffffffffffffffff604435818111610140576100fa90369084016102db565b50506064358181116101405761011390369084016102db565b50506084359081116100ae5761012c92503691016102ad565b505060405163bc197c8160e01b8152602090f35b8380fd5b50346100b25760803660031901126100b25761015e61027c565b50610167610297565b5060643567ffffffffffffffff81116100ae5761018792503691016102ad565b5050604051630a85bd0160e11b8152602090f35b919050346100ae5760203660031901126100ae573563ffffffff60e01b81168091036100ae5760209250630a85bd0160e11b81149081156101f6575b81156101e5575b5015158152f35b6301ffc9a760e01b149050386101de565b630271189760e51b811491506101d7565b5050346100b25760c03660031901126100b25761022261027c565b5061022b610297565b506044356001600160a01b038116036100b25767ffffffffffffffff906084358281116101405761025f90369083016102ad565b505060a4359182116100ae57610277913691016102ad565b505080f35b600435906001600160a01b038216820361029257565b600080fd5b602435906001600160a01b038216820361029257565b9181601f840112156102925782359167ffffffffffffffff8311610292576020838186019501011161029257565b9181601f840112156102925782359167ffffffffffffffff8311610292576020808501948460051b0101116102925756fea264697066735822122093efb10dca658022559fcc7e39f837a297fac8f03c938fd889e50f0a7e2bb22264736f6c63430008110033";

type TokenCallbackHandlerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TokenCallbackHandlerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TokenCallbackHandler__factory extends ContractFactory {
  constructor(...args: TokenCallbackHandlerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TokenCallbackHandler & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TokenCallbackHandler__factory {
    return super.connect(runner) as TokenCallbackHandler__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TokenCallbackHandlerInterface {
    return new Interface(_abi) as TokenCallbackHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TokenCallbackHandler {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TokenCallbackHandler;
  }
}
