/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EIP712 } from "./EIP712";
export type { IERC5267 } from "./IERC5267";
export type { Math } from "./Math";
export type { ShortStrings } from "./ShortStrings";
export type { Strings } from "./Strings";
