/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Auth, AuthInterface } from "../../../contracts/auth/Auth";
import { Contract, Interface, type ContractRunner } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "entrypoint",
    outputs: [
      {
        internalType: "contract IEntryPoint",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Auth__factory {
  static readonly abi = _abi;
  static createInterface(): AuthInterface {
    return new Interface(_abi) as AuthInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Auth {
    return new Contract(address, _abi, runner) as unknown as Auth;
  }
}
