/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  EntrypointAuth,
  EntrypointAuthInterface,
} from "../../../contracts/auth/EntrypointAuth";
import { Contract, Interface, type ContractRunner } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "entrypoint",
    outputs: [
      {
        internalType: "contract IEntryPoint",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class EntrypointAuth__factory {
  static readonly abi = _abi;
  static createInterface(): EntrypointAuthInterface {
    return new Interface(_abi) as EntrypointAuthInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EntrypointAuth {
    return new Contract(address, _abi, runner) as unknown as EntrypointAuth;
  }
}
