/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as erc721 from "./ERC721";
import type * as erc777 from "./ERC777";
import type * as erc1155 from "./ERC1155";

export type { erc1155 };

export type { erc721 };

export type { erc777 };
