/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1271Handler__factory } from "./ERC1271Handler__factory";
export { ValidationHandler__factory } from "./ValidationHandler__factory";
