/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iHookSol from "./IHook.sol";
export * as iValidatorSol from "./IValidator.sol";
export { IClave__factory } from "./IClave__factory";
export { IClaveRegistry__factory } from "./IClaveRegistry__factory";
export { IInitable__factory } from "./IInitable__factory";
export { IModule__factory } from "./IModule__factory";
