/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export { CloudRecoveryModule__factory } from "./CloudRecoveryModule__factory";
export { SocialRecoveryModule__factory } from "./SocialRecoveryModule__factory";
