/**
 * Copyright Clave - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export declare namespace ERC1271Handler {
  export type ClaveMessageStruct = { signedHash: BytesLike };

  export type ClaveMessageStructOutput = [signedHash: string] & {
    signedHash: string;
  };
}

export interface ERC1271HandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claveMessageTypeHash"
      | "eip712Domain"
      | "entrypoint"
      | "getEip712Hash"
      | "isHook"
      | "isModule"
      | "isValidSignature"
      | "k1AddOwner"
      | "k1AddValidator"
      | "k1IsOwner"
      | "k1IsValidator"
      | "k1ListOwners"
      | "k1ListValidators"
      | "k1RemoveOwner"
      | "k1RemoveValidator"
      | "r1AddOwner"
      | "r1AddValidator"
      | "r1IsOwner"
      | "r1IsValidator"
      | "r1ListOwners"
      | "r1ListValidators"
      | "r1RemoveOwner"
      | "r1RemoveValidator"
      | "resetOwners"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "K1AddOwner"
      | "K1AddValidator"
      | "K1RemoveOwner"
      | "K1RemoveValidator"
      | "R1AddOwner"
      | "R1AddValidator"
      | "R1RemoveOwner"
      | "R1RemoveValidator"
      | "ResetOwners"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claveMessageTypeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entrypoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEip712Hash",
    values: [ERC1271Handler.ClaveMessageStruct]
  ): string;
  encodeFunctionData(functionFragment: "isHook", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "isModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "k1AddOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "k1AddValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "k1IsOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "k1IsValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "k1ListOwners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "k1ListValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "k1RemoveOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "k1RemoveValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "r1AddOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "r1AddValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "r1IsOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "r1IsValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "r1ListOwners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "r1ListValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "r1RemoveOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "r1RemoveValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetOwners",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claveMessageTypeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entrypoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEip712Hash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isHook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isModule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "k1AddOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "k1AddValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "k1IsOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "k1IsValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "k1ListOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "k1ListValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "k1RemoveOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "k1RemoveValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "r1AddOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "r1AddValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "r1IsOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "r1IsValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "r1ListOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "r1ListValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "r1RemoveOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "r1RemoveValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetOwners",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace K1AddOwnerEvent {
  export type InputTuple = [addr: AddressLike];
  export type OutputTuple = [addr: string];
  export interface OutputObject {
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace K1AddValidatorEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace K1RemoveOwnerEvent {
  export type InputTuple = [addr: AddressLike];
  export type OutputTuple = [addr: string];
  export interface OutputObject {
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace K1RemoveValidatorEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace R1AddOwnerEvent {
  export type InputTuple = [pubKey: BytesLike];
  export type OutputTuple = [pubKey: string];
  export interface OutputObject {
    pubKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace R1AddValidatorEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace R1RemoveOwnerEvent {
  export type InputTuple = [pubKey: BytesLike];
  export type OutputTuple = [pubKey: string];
  export interface OutputObject {
    pubKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace R1RemoveValidatorEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResetOwnersEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC1271Handler extends BaseContract {
  connect(runner?: ContractRunner | null): ERC1271Handler;
  waitForDeployment(): Promise<this>;

  interface: ERC1271HandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claveMessageTypeHash: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  entrypoint: TypedContractMethod<[], [string], "view">;

  getEip712Hash: TypedContractMethod<
    [claveMessage: ERC1271Handler.ClaveMessageStruct],
    [string],
    "view"
  >;

  isHook: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isModule: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isValidSignature: TypedContractMethod<
    [signedHash: BytesLike, signatureAndValidator: BytesLike],
    [string],
    "view"
  >;

  k1AddOwner: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  k1AddValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  k1IsOwner: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  k1IsValidator: TypedContractMethod<
    [validator: AddressLike],
    [boolean],
    "view"
  >;

  k1ListOwners: TypedContractMethod<[], [string[]], "view">;

  k1ListValidators: TypedContractMethod<[], [string[]], "view">;

  k1RemoveOwner: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  k1RemoveValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  r1AddOwner: TypedContractMethod<[pubKey: BytesLike], [void], "nonpayable">;

  r1AddValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  r1IsOwner: TypedContractMethod<[pubKey: BytesLike], [boolean], "view">;

  r1IsValidator: TypedContractMethod<
    [validator: AddressLike],
    [boolean],
    "view"
  >;

  r1ListOwners: TypedContractMethod<[], [string[]], "view">;

  r1ListValidators: TypedContractMethod<[], [string[]], "view">;

  r1RemoveOwner: TypedContractMethod<[pubKey: BytesLike], [void], "nonpayable">;

  r1RemoveValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  resetOwners: TypedContractMethod<[pubKey: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claveMessageTypeHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "entrypoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEip712Hash"
  ): TypedContractMethod<
    [claveMessage: ERC1271Handler.ClaveMessageStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isHook"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isModule"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<
    [signedHash: BytesLike, signatureAndValidator: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "k1AddOwner"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "k1AddValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "k1IsOwner"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "k1IsValidator"
  ): TypedContractMethod<[validator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "k1ListOwners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "k1ListValidators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "k1RemoveOwner"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "k1RemoveValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "r1AddOwner"
  ): TypedContractMethod<[pubKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "r1AddValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "r1IsOwner"
  ): TypedContractMethod<[pubKey: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "r1IsValidator"
  ): TypedContractMethod<[validator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "r1ListOwners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "r1ListValidators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "r1RemoveOwner"
  ): TypedContractMethod<[pubKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "r1RemoveValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetOwners"
  ): TypedContractMethod<[pubKey: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "K1AddOwner"
  ): TypedContractEvent<
    K1AddOwnerEvent.InputTuple,
    K1AddOwnerEvent.OutputTuple,
    K1AddOwnerEvent.OutputObject
  >;
  getEvent(
    key: "K1AddValidator"
  ): TypedContractEvent<
    K1AddValidatorEvent.InputTuple,
    K1AddValidatorEvent.OutputTuple,
    K1AddValidatorEvent.OutputObject
  >;
  getEvent(
    key: "K1RemoveOwner"
  ): TypedContractEvent<
    K1RemoveOwnerEvent.InputTuple,
    K1RemoveOwnerEvent.OutputTuple,
    K1RemoveOwnerEvent.OutputObject
  >;
  getEvent(
    key: "K1RemoveValidator"
  ): TypedContractEvent<
    K1RemoveValidatorEvent.InputTuple,
    K1RemoveValidatorEvent.OutputTuple,
    K1RemoveValidatorEvent.OutputObject
  >;
  getEvent(
    key: "R1AddOwner"
  ): TypedContractEvent<
    R1AddOwnerEvent.InputTuple,
    R1AddOwnerEvent.OutputTuple,
    R1AddOwnerEvent.OutputObject
  >;
  getEvent(
    key: "R1AddValidator"
  ): TypedContractEvent<
    R1AddValidatorEvent.InputTuple,
    R1AddValidatorEvent.OutputTuple,
    R1AddValidatorEvent.OutputObject
  >;
  getEvent(
    key: "R1RemoveOwner"
  ): TypedContractEvent<
    R1RemoveOwnerEvent.InputTuple,
    R1RemoveOwnerEvent.OutputTuple,
    R1RemoveOwnerEvent.OutputObject
  >;
  getEvent(
    key: "R1RemoveValidator"
  ): TypedContractEvent<
    R1RemoveValidatorEvent.InputTuple,
    R1RemoveValidatorEvent.OutputTuple,
    R1RemoveValidatorEvent.OutputObject
  >;
  getEvent(
    key: "ResetOwners"
  ): TypedContractEvent<
    ResetOwnersEvent.InputTuple,
    ResetOwnersEvent.OutputTuple,
    ResetOwnersEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "K1AddOwner(address)": TypedContractEvent<
      K1AddOwnerEvent.InputTuple,
      K1AddOwnerEvent.OutputTuple,
      K1AddOwnerEvent.OutputObject
    >;
    K1AddOwner: TypedContractEvent<
      K1AddOwnerEvent.InputTuple,
      K1AddOwnerEvent.OutputTuple,
      K1AddOwnerEvent.OutputObject
    >;

    "K1AddValidator(address)": TypedContractEvent<
      K1AddValidatorEvent.InputTuple,
      K1AddValidatorEvent.OutputTuple,
      K1AddValidatorEvent.OutputObject
    >;
    K1AddValidator: TypedContractEvent<
      K1AddValidatorEvent.InputTuple,
      K1AddValidatorEvent.OutputTuple,
      K1AddValidatorEvent.OutputObject
    >;

    "K1RemoveOwner(address)": TypedContractEvent<
      K1RemoveOwnerEvent.InputTuple,
      K1RemoveOwnerEvent.OutputTuple,
      K1RemoveOwnerEvent.OutputObject
    >;
    K1RemoveOwner: TypedContractEvent<
      K1RemoveOwnerEvent.InputTuple,
      K1RemoveOwnerEvent.OutputTuple,
      K1RemoveOwnerEvent.OutputObject
    >;

    "K1RemoveValidator(address)": TypedContractEvent<
      K1RemoveValidatorEvent.InputTuple,
      K1RemoveValidatorEvent.OutputTuple,
      K1RemoveValidatorEvent.OutputObject
    >;
    K1RemoveValidator: TypedContractEvent<
      K1RemoveValidatorEvent.InputTuple,
      K1RemoveValidatorEvent.OutputTuple,
      K1RemoveValidatorEvent.OutputObject
    >;

    "R1AddOwner(bytes)": TypedContractEvent<
      R1AddOwnerEvent.InputTuple,
      R1AddOwnerEvent.OutputTuple,
      R1AddOwnerEvent.OutputObject
    >;
    R1AddOwner: TypedContractEvent<
      R1AddOwnerEvent.InputTuple,
      R1AddOwnerEvent.OutputTuple,
      R1AddOwnerEvent.OutputObject
    >;

    "R1AddValidator(address)": TypedContractEvent<
      R1AddValidatorEvent.InputTuple,
      R1AddValidatorEvent.OutputTuple,
      R1AddValidatorEvent.OutputObject
    >;
    R1AddValidator: TypedContractEvent<
      R1AddValidatorEvent.InputTuple,
      R1AddValidatorEvent.OutputTuple,
      R1AddValidatorEvent.OutputObject
    >;

    "R1RemoveOwner(bytes)": TypedContractEvent<
      R1RemoveOwnerEvent.InputTuple,
      R1RemoveOwnerEvent.OutputTuple,
      R1RemoveOwnerEvent.OutputObject
    >;
    R1RemoveOwner: TypedContractEvent<
      R1RemoveOwnerEvent.InputTuple,
      R1RemoveOwnerEvent.OutputTuple,
      R1RemoveOwnerEvent.OutputObject
    >;

    "R1RemoveValidator(address)": TypedContractEvent<
      R1RemoveValidatorEvent.InputTuple,
      R1RemoveValidatorEvent.OutputTuple,
      R1RemoveValidatorEvent.OutputObject
    >;
    R1RemoveValidator: TypedContractEvent<
      R1RemoveValidatorEvent.InputTuple,
      R1RemoveValidatorEvent.OutputTuple,
      R1RemoveValidatorEvent.OutputObject
    >;

    "ResetOwners()": TypedContractEvent<
      ResetOwnersEvent.InputTuple,
      ResetOwnersEvent.OutputTuple,
      ResetOwnersEvent.OutputObject
    >;
    ResetOwners: TypedContractEvent<
      ResetOwnersEvent.InputTuple,
      ResetOwnersEvent.OutputTuple,
      ResetOwnersEvent.OutputObject
    >;
  };
}
